apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm
  namespace: genai-platform
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: genai-platform
  source:
    repoURL: 'https://git.eon-cds.de/repos/ai-workstation/service/genai-platform/genai-proxy-sever.git'  # Replace with your Git repository URL
    path: 'litellm'  # Path to the directory containing your manifests (if different)
    targetRevision: HEAD
  project: genai-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true