apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm
  namespace: genai-platform
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: genai-platform
  source:
    repoURL: 'https://git.eon-cds.de/repos/mlops-poc/genai/proxy-app-config.git'  # Replace with your Git repository URL
    path: '/litellm'  # Path to the directory containing your manifests (if different)
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true