apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-deployment
spec:
  selector:
    matchLabels:
      app: litellm
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: litellm
      annotations:
        secrets-store.csi.k8s.io/secret-objects: |
          array:
            - |
              secretName: azure-secrets
              type: Opaque
              data: 
              - objectName: psql-secret
                key: PSQL_CONN_STR        
    spec:
      containers:
      - name: litellm-container
        image: ghcr.io/berriai/litellm:main-latest   
        volumeMounts:
        - name: litellm-config-volume
          mountPath: /etc/config
        args: [ "--port", "$(PORT)" , "--config", "/etc/config/litellmProxyConfig",]
        env:
          - name: PSQL_CONN_STR
            valueFrom:
              secretKeyRef:
                name: azure-secrets
                key: PSQL_CONN_STR          
          - name: MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: litellm-secrets
                key: MASTER_KEY
          - name: AZURE_API_KEY
            valueFrom:
              secretKeyRef:
                name: litellm-secrets
                key: AZURE_API_KEY
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: litellm-config
                key: CONTAINER_PORT        
        ports:
        - containerPort: 4001
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-keyvault"        
        - name: litellm-config-volume
          configMap:
            name: litellm-config
            items:
            - key: LITELLM-PROXY-CONFIG
              path: litellmProxyConfig          