apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "genai-platform-keyvault" 
    objects: |
      array:
        - |
          objectName: psqlConnectionStr
          objectType: secret
    tenantId: "b914a242-e718-443b-a47c-6b4c649d8c0a"